version: "3.7"
services:
  db:
    image: fcumselab/fcu-progedu-mysql:release-2.0.4
    ports:
      - "${DB_PORT}:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql:/var/lib/mysql

  gitlab:
    image: gitlab/gitlab-ce:12.5.6-ce.0
    deploy:
      resources:
        limits:
          memory: 3072M
    ports:
      - "${GITLAB_HTTP_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"
    restart: always
    privileged: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_HOST}'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['initial_root_password'] = "${GITLAB_ROOT_PASSWORD}"
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

  server:
    image: fcumselab/progedu-tomcat:latest
    build:
      context: ./server
      args:
        - DEBUG=false
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:8080"
    restart: always
    depends_on:
      - db
      - jenkins
      - gitlab
    volumes:
      - server-temp:/usr/local/tomcat/temp
      - server-logs:/usr/local/tomcat/logs
      - server-images:/usr/local/tomcat/images
  
      
  front-end:
    build:
      context: ./front
      args:
        - BACK_END_URL=${WEB_EXTERNAL_URL}
    ports:
      - "${FRONT_END_PORT}:80"
    restart: always
    

  jenkins:
    image: fcumselab/fcu-progedu-jenkins:release-1.0.0
    deploy:
      resources:
        limits:
          memory: 1024M
    ports:
      - "${JENKINS_PORT}:8080"
    restart: always
    privileged: true
    environment:
      WEB_SELENIUM_URL: ${WEB_SELENIUM_URL}
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_home-workspace:/var/jenkins_home/workspace
      # - /dev/kvm:/dev/kvm // for android, but now it not need

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "${SELENIUM_PORT}:4444"
    restart: always
    volumes:
      - jenkins_home-workspace:/var/lib/workspace

  mongo:
    image: fcumselab/progedu-mongo:release-1.0.1
    ports:
      - "${MONGO_PORT}:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo:/data/db
    command: mongod --auth
    
    
volumes:

  mysql: {}
  
  gitlab-config: {}
  gitlab-logs: {}
  gitlab-data: {}
  
  server-temp: {}
  server-logs: {}
  server-images: {}
  
  jenkins_home: {}
  jenkins_home-workspace: {}
  
  mongo: {}